//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputSystem/New Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @NewControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @NewControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""New Controls"",
    ""maps"": [
        {
            ""name"": ""TestPlayer"",
            ""id"": ""5ff1417e-7fbe-4d19-aaef-3e228715b2a7"",
            ""actions"": [
                {
                    ""name"": ""OnLook"",
                    ""type"": ""Value"",
                    ""id"": ""0676c9a5-7e9a-4ece-a780-5a293fc5a152"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4c3198b0-7399-4206-9833-a90329ba9306"",
                    ""path"": ""<Touchscreen>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnLook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""New control scheme"",
            ""bindingGroup"": ""New control scheme"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // TestPlayer
        m_TestPlayer = asset.FindActionMap("TestPlayer", throwIfNotFound: true);
        m_TestPlayer_OnLook = m_TestPlayer.FindAction("OnLook", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // TestPlayer
    private readonly InputActionMap m_TestPlayer;
    private List<ITestPlayerActions> m_TestPlayerActionsCallbackInterfaces = new List<ITestPlayerActions>();
    private readonly InputAction m_TestPlayer_OnLook;
    public struct TestPlayerActions
    {
        private @NewControls m_Wrapper;
        public TestPlayerActions(@NewControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @OnLook => m_Wrapper.m_TestPlayer_OnLook;
        public InputActionMap Get() { return m_Wrapper.m_TestPlayer; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TestPlayerActions set) { return set.Get(); }
        public void AddCallbacks(ITestPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_TestPlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TestPlayerActionsCallbackInterfaces.Add(instance);
            @OnLook.started += instance.OnOnLook;
            @OnLook.performed += instance.OnOnLook;
            @OnLook.canceled += instance.OnOnLook;
        }

        private void UnregisterCallbacks(ITestPlayerActions instance)
        {
            @OnLook.started -= instance.OnOnLook;
            @OnLook.performed -= instance.OnOnLook;
            @OnLook.canceled -= instance.OnOnLook;
        }

        public void RemoveCallbacks(ITestPlayerActions instance)
        {
            if (m_Wrapper.m_TestPlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITestPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_TestPlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TestPlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TestPlayerActions @TestPlayer => new TestPlayerActions(this);
    private int m_NewcontrolschemeSchemeIndex = -1;
    public InputControlScheme NewcontrolschemeScheme
    {
        get
        {
            if (m_NewcontrolschemeSchemeIndex == -1) m_NewcontrolschemeSchemeIndex = asset.FindControlSchemeIndex("New control scheme");
            return asset.controlSchemes[m_NewcontrolschemeSchemeIndex];
        }
    }
    public interface ITestPlayerActions
    {
        void OnOnLook(InputAction.CallbackContext context);
    }
}
